const LOGGED_IN = "LOGGED_IN";
const LOGGED_OUT = "LOGGED_OUT";
const ALL_POSTS = "ALL_POSTS";
const USER_PROFILE = "USER_PROFILE";
const POST_TAGS = "POST_TAGS";
const ADD_POST="ADD_POST";
const POST_DETAILS="POST_DETAILS"
export { LOGGED_IN, LOGGED_OUT, ALL_POSTS, USER_PROFILE, POST_TAGS,ADD_POST,POST_DETAILS };
