const LOGGED_IN = "LOGGED_IN";
const LOGGED_OUT = "LOGGED_OUT";
const ALL_POSTS = "ALL_POSTS";
const USER_PROFILE = "USER_PROFILE";
const POST_TAGS = "POST_TAGS";

export { LOGGED_IN, LOGGED_OUT, ALL_POSTS, USER_PROFILE, POST_TAGS };
