const LOGGED_IN = "LOGGED_IN";
const LOGGED_OUT = "LOGGED_OUT";
const ALL_POSTS = "ALL_POSTS";
const USER_PROFILE = "USER_PROFILE";
const POST_TAGS = "POST_TAGS";
const ADD_POST = "ADD_POST";
const POST_DETAILS = "POST_DETAILS";
const ADD_COMMENT = "ADD_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";
const LIKE_POST = "LIKE_POST";
const LIKE_COMMENT = "LIKE_COMMENT";
const USER_POSTS = "USER_POSTS";
const DELETE_POST = "DELETE_POST";
const SEARCHED_USERS = "SEARCHED_USERS";

export {
	LOGGED_IN,
	SEARCHED_USERS,
	DELETE_POST,
	LOGGED_OUT,
	ALL_POSTS,
	USER_POSTS,
	POST_TAGS,
	ADD_POST,
	POST_DETAILS,
	ADD_COMMENT,
	LIKE_POST,
	DELETE_COMMENT,
	LIKE_COMMENT,
	USER_PROFILE,
};
